name: Check pods
on:
   push:
    branches:
      - 'main'
jobs:
  check:
    env:
      result_file: result.log
      channel: git-test
      GIT: ${{secrets.JUMP_IP}} 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.check.outputs.check}}
    steps:
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      id: check
      env:
        SSH_PUB: ${{secrets.SSH_PUB}}
      with:
        host: ${{secrets.JUMP_IP}}
        username: ${{ secrets.JUMP_USERNAME }}
        password: ${{ secrets.JUMP_PASS}}
