name: Check pods
on:
  push:
    branches:
      - 'main'
jobs:
  check:
    env:
       output: output.log
       fail_report: fail_report.log
    runs-on: ubuntu-latest
    steps:
    - name : Connect to remote host and get pods
      run: |
        which ssh-agent
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_KEY_2}}"
        ssh-keyscan ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} ssh-keyscan ${{ secrets.K3S_HOST }} >> ~/.ssh/known_hosts
        ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }}" ${{ secrets.K3S_USERNAME }}@${{ secrets.K3S_HOST }} "kubectl get pods -A" >> ${{ env.output }}
   
