name: Check pods
on:
  push:
    branches:
      - 'main'
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.check.outputs.check}}
    steps:
    - name: Install SSH key of bastion
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.SSH_KEY_OF_BASTION }}
          name: id_rsa-bastion
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_BASTION }}
          config: |
                Host bastion
                HostName 178.124.206.53
                User jump_sa
                IdentityFile ~/.ssh/id_rsa-bastion
   
