name: Check pods
on:
   push:
    branches:
      - 'main'
jobs:
  check:
    env:
      result_file: result.log
      channel: git-test
      GIT: ${{secrets.JUMP_IP}} 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.check.outputs.check}}
    steps:
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      id: check
      env:
        SSH_PUB: ${{secrets.SSH_PUB}}
      with:
        host: ${{secrets.JUMP_HOST}}
        username: ${{ secrets.JUMP_USERNAME }}
        password: ${{ secrets.JUMP_PASS}}
        envs: SSH_PUB
        script:  |
          echo $SSH_PUB >> ~/.ssh/k3s.pub
    - name: Add ssh and checking pods
      run: |
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        echo "$SSH_PRIVATE" > ~/.ssh/k3s
        sudo chmod 600 ~/.ssh/k3s
        ssh-add - <<< "$SSH_PRIVATE"
        ssh-keyscan -H ${{secrets.JUMP_IP}} >> ~/.ssh/known_hosts
        ssh ${{ secrets.JUMP_USERNAME}}@${{secrets.JUMP_HOST}} ssh-keyscan ${{ secrets.K3S_HOST }} >> ~/.ssh/known_hosts
        sshpass -p ${{ secrets.K3S_PASS }} ssh -oProxyCommand="sshpass ssh -W %h:%p ${{ secrets.JUMP_USERNAME}}@${{secrets.JUMP_HOST}}" root@${{ secrets.K3S_HOST }} "kubectl get pods -A" >> ${{ env.result_file}}  
      shell: bash
      env:
        SSH_PRIVATE: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_PUBLIC: ${{secrets.SSH_PUB}}
