name: Check pods
on:
  push:
    branches:
      - 'main'
jobs:
  check: 
    runs-on: ubuntu-latest
    env:
       output: output.log
    steps:
    - name : Connect to host
      run: |
        which ssh-agent
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_KEY}}"
        ssh-keyscan ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} ssh-keyscan ${{ secrets.K3S_HOST }} >> ~/.ssh/known_hosts
        ssh "${{ secrets.K3S_USERNAME }}"@"${{ secrets.K3S_HOST }}" \
          -o ProxyCommand="ssh -W %h:%p -q "${{secrets.JUMP_USERNAME}}"@"${{secrets.JUMP_HOST}}"" \
          kubectl get pods -A >> report
