name: Check pods
 schedule:
   - cron: '*/10 * * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      report-file: report.log
    steps:
   - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      id: check
      env:
        SSH_PUB: ${{ secrets.SSH_PUB }}
      with:
        host: ${{ secrets.JUMP_HOST }}
        username: ${{ secrets.JUMP_USERNAME }}
        password: ${{ secrets.JUMP_PASS}}
        envs: SSH_PUB
        script: |
                 echo $SSH_PUB >> ~/.ssh/k3s.pub
