name: Check pods
on:
  push:
      branches: ["main"]
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      report-file: report.log
    steps:
      - name: SSH to remote host
        id: get-pods
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-keyscan -H ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts
          ssh  ${{ secrets.JUMP_USERNAME }}@{{secrets.JUMP_HOST}}
          ip a >> report-file
          
      - name: upload crashed pod's list
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.report-file }}
          
          
