name: Check pods
on:
  push:
    branches:
      - 'main'
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.check.outputs.check}}
    steps:
    - name: Add SSH key and connect to k3s
      run: |
         mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          ssh "${{ secrets.K3S_USERNAME }}"@"${{ secrets.K3S_HOST }}" \
          -o ProxyCommand="ssh -W %h:%p -q "${{secrets.JUMP_USERNAME}}"@"${{secrets.JUMP_HOST}}"" \
          kubectl get pods -A


