name: Check pods
on:
  push:
      branches: ["main"]
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      report-file: report.log
    steps:
      - name: SSH to remote host
        id: get-pods
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"  
